### ISSUE TITLE
Development environment and configuration

### ISSUE THREAD

**Issue by andersonsantos** [rjmreis/hapi-api#2]
Hi Ricardo!
Could you please share more information about the VS Code configuration and plugins that you used?
For example, I'm using JSCS to check my code style... I tried 'google', 'airbnb' and 'idiomatic' but none matched 100% the style of this source.

Thanks!

**Comment by andersonsantos** [comment]
P.s.: I suspect that you are using VS Code because I saw the '.vscode' and 'typings' inside .gitignore

**Comment by rjmreis** [comment]
Hey Anderson!
Actually I've only started using VS Code, really dig it as it's very light and quite powerful. I don't use any plugin as of now, but I do use the tsd definitions for different libraries.
And well guessed man! Will actually try that JSCS one.

Thanks

**Comment by andersonsantos** [comment]
Sorry for the delay! Thanks for the reply Ricardo!
You should try JSCS, nice tool to keep your coding style in check ;)
